#!/usr/bin/env bash
# Displays 'Best School' 10 times.

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]; then
		echo -e "Best School\nHi"
		x=$(( $x + 1 ))
	else
		echo 'Best School'
		x=$(( $x + 1 ))
	fi
done
