#!/usr/bin/env bash
# Gives information about the school file.

school="school"
# check if file exists
if [ -e "$school" ]
then
	echo "school file exists"
else
	echo "school file does not exist"
fi

# check if file is empty
if [ -s "$school" ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

# check if file is regular file
if [ -f "$school" ]
then
	echo "shool is a regular file"
fi
